# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=7282
@host={{hostname}}:{{port}}
@id=a1b3c97b-1841-4307-9f7c-49759d635021

### Get all todo items

GET https://{{host}}/todoitems

### Create a new todo item

POST https://{{host}}/todoitems
Content-Type: application/json

{
  "title": "Do laundry",
  "description": "Do the laundry"
}

### Mark a todo item done

PATCH https://{{host}}/todoitems/{{id}}/MarkDone

### Move to new list

PATCH https://{{host}}/todoitems/{{id}}/MoveToNewList?listId=list2